server:
  mode: debug # debug/test/release
  ip: 0.0.0.0
  port: 28080

selected_module:
  asr: paraformer
  llm: qwen
  tts: cosy_voice

asr:
  paraformer:
    api_key: <your api_key>
  doubao:
    app_id: <your app_id>
    access_token: <your access_token>

llm:
  qwen:
    model: qwen2.5-72b-instruct
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    api_key: <your api_key>

tts:
  cosy_voice:
    api_key: <your api_key>
  doubao:
    app_id: <your app_id>
    token: <your access_token>
    cluster: <your cluster>
  doubao_stream: # 双流式，如果使用豆包，推荐用这个
    app_id: <your app_id>
    token: <your access_token>
    cluster: <your cluster>
    resource_id: volc.service_type.10029

cmd_exit:
  - "退出"
  - "关闭"
  - "exit"
  - "close"
